[package]
name = "pause_menu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28.0"
ntapi = "0.4.1"
sysinfo = "0.30.12"
winapi = { version = "0.3.9", features = ["processthreadsapi"] }
